name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build Docker image and push to repo
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lowercasing names for docker
        run: |
          echo "GIT_ACTOR=${ACTOR,,}" >>${GITHUB_ENV}
          echo "GIT_REPO=${REPO,,}" >>${GITHUB_ENV}
        env:
          ACTOR: '${{ github.actor }}'
          REPO: '${{ github.repository }}'
  
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GIT_ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to Docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: Dockerfile
          tags: ghcr.io/${{ env.GIT_REPO }}:latest
      
      - name: Deploying to server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker image pull kboruph/petstore:latest
            docker container stop petstore
            docker container rm petstore
            docker container run -d --name petstore -p 80:5000 kboruph/petstore:latest
            
        
